name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-307.0.dev <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1

  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  meta: ^1.9.0

