// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaB_Gel86eutQ_8miYlB9cHPwwWMuQJf0',
    appId: '1:1030211861772:web:cade4e0c84f64893a65d29',
    messagingSenderId: '1030211861772',
    projectId: 'pastry-6b817',
    authDomain: 'pastry-6b817.firebaseapp.com',
    storageBucket: 'pastry-6b817.appspot.com',
    measurementId: 'G-SVNDR2S2H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABf3s_Po9SL8V8fqkUiUdyQbtievofqTk',
    appId: '1:1030211861772:android:33869bdbf07c2128a65d29',
    messagingSenderId: '1030211861772',
    projectId: 'pastry-6b817',
    storageBucket: 'pastry-6b817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxgYIPrE6QCMoZpRc6gWPssHELQzBwqE',
    appId: '1:1030211861772:ios:dfaa340eef008007a65d29',
    messagingSenderId: '1030211861772',
    projectId: 'pastry-6b817',
    storageBucket: 'pastry-6b817.appspot.com',
    iosClientId:
        '1030211861772-4b2tc2m8j0i23gd3opk2q5fc024psoq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pastry',
  );
}
