name: repositories
description: Dart package which manages the repositories.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  authentication_repository:
    path: ../authentication_repository

  flutter:
    sdk: flutter
  meta:
