name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: master
      - run: flutter pub get
      - run: flutter test
      - uses: Pastry-Flutter/flutter-gh-pages@v7
        with:
          baseHref: /test/
